#!/bin/bash
# =============================================================
# TiX-One Step 4: Create Waitlist objects on-chain per concert
# Run ONCE after 2-seed-concerts.sh.
# Creates one shared Waitlist per concert and outputs full
# Supabase SQL to update both concert_object_id AND waitlist_object_id.
# =============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDS_FILE="$SCRIPT_DIR/.deployed-ids.env"
SQL_FILE="$SCRIPT_DIR/supabase-update.sql"

# ---- Load deployed IDs ----
if [ ! -f "$IDS_FILE" ]; then
  echo "❌  $IDS_FILE not found."
  echo "    Run scripts/1-deploy.sh first."
  exit 1
fi
source "$IDS_FILE"

if [ -z "$PACKAGE_ID" ] || [ -z "$ADMIN_CAP_ID" ]; then
  echo "❌  PACKAGE_ID or ADMIN_CAP_ID is missing in $IDS_FILE"
  exit 1
fi

echo ""
echo "⏳  Creating Waitlist objects on-chain..."
echo "    Package   : $PACKAGE_ID"
echo "    Admin Cap : $ADMIN_CAP_ID"
echo ""

# ---- Concert data: "supabase_id|concert_object_id|face_value_mist|artist|event_name|concert_datetime_utc" ----
# concert_datetime_utc format: "YYYY-MM-DD HH:MM"  (UTC) — used for expires_at (Unix ms)
# These concert_object_ids were captured by 2-seed-concerts.sh
declare -a DATA=(
  "1|0x5971f5df9e45735f1521a912af63a1cdba46af80cf7ecd91b0dbb9d25615c291|50000000|Martin Garrix|Neon Dreams Tour|2026-02-28 20:00"
  "2|0x2061d3e4a091229dd0529dd13f9027da2e5dfd15a3963fc0c8cdc65095303070|80000000|Taylor Swift|Celestial Sound Experience|2026-03-14 19:30"
  "3|0xf1811ad9a458702ecffe85104223f3969d8e46d4d8791bec7d6cb7e4fc286f74|120000000|Calvin Harris|Blockchain Beats Festival|2026-04-05 18:00"
  "4|0x2c8fd04b39739ae0049e9e1601000f987a620ca8c571b027b0a42eae3bd9cac6|40000000|Ed Sheeran|Unplugged & Unchained|2026-04-12 20:00"
  "5|0x3fa74a4a8ceec075b2979a0c1a99fed3539246a5201f8c07bc58dc413b28b635|70000000|Drake|Decentralized Sound Tour|2026-04-20 21:00"
  "6|0x86659dd9d283bc3c3f8d5515aab157353a60244e6815ad4540141aec91d88d89|60000000|Billie Eilish|Galaxy Tour 2026|2026-05-01 19:00"
  "7|0xc399dd4365c160e74cf6c2200c3acd9585b555d816eb28334193b3ffc3d14470|30000000|Bruno Mars|Smooth Grooves Night|2026-05-08 21:30"
  "8|0xcc47a1ef7f7b365365ece68662022c5bfee027d9e55323df5a0cfcce1b493a2c|90000000|The Weeknd|Rock Revolution Tour|2026-05-15 20:00"
  "9|0xae9298f9f3d31c24d185c3b7be9740f76eea447e9638118c9d72556f72e5c8e2|100000000|Coldplay|Blockchain Classics|2026-06-01 19:00"
  "10|0x0e0e30697349ecbfd3bc377a6e1f457e2a384f32f5f3947fa45e00a974a2557d|45000000|Post Malone|Country Roads Festival|2026-06-10 18:30"
  "11|0x9ba6a188ef9a92061be10c38ca952f5da30440c14a5c288ba4c94a45bdc206cd|70000000|Linkin Park|Metal Mayhem World Tour|2026-06-18 21:00"
  "12|0x32f0f32567b9ec3ff89a714012d5d1b0a466d74e14fc5892c904ba2c6b39b706|35000000|Rihanna|Island Rhythms Festival|2026-07-04 17:00"
  "13|0x15470e0181b4d2f822ae99e91073f6b60781a6da524fb8485942f96a6418d3f3|55000000|Shakira|Salsa Heat Night|2026-07-12 22:00"
  "14|0x5f4e6db6e9bdc3f77eab67c18d9edb9879d71e77eadd90d2bb162d9f3ec8e734|65000000|Dua Lipa|Techno Underground|2026-07-22 23:00"
  "15|0x688488eee54d7202390353a9efc8fdeb3355a8586009ddff1e86dd126bf4aea1|50000000|Adele|Blues Heritage Tour|2026-08-03 20:30"
)

# ---- Begin SQL file ----
cat > "$SQL_FILE" << 'SQLHEADER'
-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

SQLHEADER

FAILED=0

for entry in "${DATA[@]}"; do
  IFS='|' read -r SUPABASE_ID CONCERT_OBJECT_ID FACE_VALUE ARTIST EVENT_NAME CONCERT_DATE <<< "$entry"

  # Convert "YYYY-MM-DD HH:MM" UTC to Unix milliseconds for expires_at
  EXPIRES_AT=$(python3 -c "
import calendar, datetime
dt = datetime.datetime.strptime('$CONCERT_DATE', '%Y-%m-%d %H:%M')
print(int(calendar.timegm(dt.timetuple())) * 1000)
")

  echo -n "  [$SUPABASE_ID] $EVENT_NAME (expires_at=${EXPIRES_AT}) ... "

  RESULT=$(one client call \
    --package "$PACKAGE_ID" \
    --module ticket \
    --function create_waitlist \
    --args "$ADMIN_CAP_ID" "$CONCERT_OBJECT_ID" "$FACE_VALUE" "$EXPIRES_AT" \
    --gas-budget 10000000 \
    --json 2>/dev/null)

  WAITLIST_ID=$(echo "$RESULT" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for c in data.get('objectChanges', []):
    t = c.get('objectType', '')
    if '::ticket::Waitlist' in t and c.get('type') == 'created':
        print(c['objectId'])
        break
" 2>/dev/null)

  if [ -z "$WAITLIST_ID" ]; then
    echo "❌  FAILED"
    FAILED=$((FAILED + 1))
    echo "-- ❌ FAILED: $EVENT_NAME (id=$SUPABASE_ID)" >> "$SQL_FILE"
    continue
  fi

  echo "✅  $WAITLIST_ID"

  # Derive OCT price string
  PRICE_OCT=$(python3 -c "
mist = $FACE_VALUE
oct_val = mist / 1_000_000_000
s = f'{oct_val:.9f}'.rstrip('0')
if '.' in s:
    parts = s.split('.')
    dec = parts[1] if len(parts[1]) >= 2 else parts[1].ljust(2, '0')
    s = parts[0] + '.' + dec
print(s + ' OCT')
")

  cat >> "$SQL_FILE" << SQLROW
UPDATE concerts
SET concert_object_id   = '$CONCERT_OBJECT_ID',
    waitlist_object_id  = '$WAITLIST_ID',
    artist              = '$ARTIST',
    "availableTickets"  = 2,
    price               = '$PRICE_OCT'
WHERE id = '$SUPABASE_ID';   -- $EVENT_NAME

SQLROW

done

echo ""
if [ "$FAILED" -gt 0 ]; then
  echo "⚠️   $FAILED waitlist(s) failed — check output above."
else
  echo "🎉  All waitlists created successfully!"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NEXT STEP:"
echo "  1. Open Supabase → SQL Editor"
echo "  2. Paste the contents of:"
echo "     $SQL_FILE"
echo "  3. Run the query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
