-- ============================================================
-- Supabase: paste this into the SQL Editor to link on-chain IDs
-- Generated by scripts/2-seed-concerts.sh
-- ============================================================

UPDATE concerts
SET concert_object_id   = '0xe2037db56d1b005997812b260b9fd083498364810dbe99b2f3292ac0404043cf',
    artist              = 'Martin Garrix',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '1';   -- Neon Dreams Tour

UPDATE concerts
SET concert_object_id   = '0x3d627958197aa8deade426a5cbb6a1643fc60c0bf0a325e5b09b8d9821089691',
    artist              = 'Taylor Swift',
    "availableTickets"  = 2,
    price               = '0.08 OCT'
WHERE id = '2';   -- Celestial Sound Experience

UPDATE concerts
SET concert_object_id   = '0x8c0ea5302b753a39bedd3290d75fcc5bf7c0e7d0b14c0c2a824f4400f7e58cd5',
    artist              = 'Calvin Harris',
    "availableTickets"  = 2,
    price               = '0.12 OCT'
WHERE id = '3';   -- Blockchain Beats Festival

UPDATE concerts
SET concert_object_id   = '0xcc389a9a007e20b7241d6c9a025161c03a998837b41e031aa7402bb09fc0b760',
    artist              = 'Ed Sheeran',
    "availableTickets"  = 2,
    price               = '0.04 OCT'
WHERE id = '4';   -- Unplugged & Unchained

UPDATE concerts
SET concert_object_id   = '0xa22ef24292e20c468b92bf1b9bb40cee1ffdfb94bbbfec638efff8f8e2d8cc24',
    artist              = 'Drake',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '5';   -- Decentralized Sound Tour

UPDATE concerts
SET concert_object_id   = '0x007c6900561b72670052de214f061caecf85c6f5dffa965f71d36e32bd218150',
    artist              = 'Billie Eilish',
    "availableTickets"  = 2,
    price               = '0.06 OCT'
WHERE id = '6';   -- Galaxy Tour 2026

UPDATE concerts
SET concert_object_id   = '0xe5792e3598af5c44da9872df8f350e7b6e7ed0277b8896f570b432d2f586654e',
    artist              = 'Bruno Mars',
    "availableTickets"  = 2,
    price               = '0.03 OCT'
WHERE id = '7';   -- Smooth Grooves Night

UPDATE concerts
SET concert_object_id   = '0xa373953ccca28baad7ab660141da0baeb67098616469fa183d97bb658066af16',
    artist              = 'The Weeknd',
    "availableTickets"  = 2,
    price               = '0.09 OCT'
WHERE id = '8';   -- Rock Revolution Tour

UPDATE concerts
SET concert_object_id   = '0x630066f8c98e99f44ff5b69c2a561dbe41c82c160d0db0277d5d34500c8a67df',
    artist              = 'Coldplay',
    "availableTickets"  = 2,
    price               = '0.10 OCT'
WHERE id = '9';   -- Blockchain Classics

UPDATE concerts
SET concert_object_id   = '0x9b5ee3b9c1bacdede71ec731bacb71656db00667f5fa726bdedb81fbf14ba0b2',
    artist              = 'Post Malone',
    "availableTickets"  = 2,
    price               = '0.045 OCT'
WHERE id = '10';   -- Country Roads Festival

UPDATE concerts
SET concert_object_id   = '0xad8033fc892b3b2cf053e6d87cfd12efd30c88c90c052d92b04cd0cba0d3c858',
    artist              = 'Linkin Park',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '11';   -- Metal Mayhem World Tour

UPDATE concerts
SET concert_object_id   = '0xa1bd7fea6a1fb0266e277611e0089ee4c820fde0e391e019b4817ec136314f5d',
    artist              = 'Rihanna',
    "availableTickets"  = 2,
    price               = '0.035 OCT'
WHERE id = '12';   -- Island Rhythms Festival

UPDATE concerts
SET concert_object_id   = '0x8ba1bbc2596ebdb3ac8dcc93502a2da68b64b21128a05064097fb4d7c73a88c1',
    artist              = 'Shakira',
    "availableTickets"  = 2,
    price               = '0.055 OCT'
WHERE id = '13';   -- Salsa Heat Night

UPDATE concerts
SET concert_object_id   = '0x8e3a121941cdf6c7cd162cac4bc065894ddd3346fa4ad7296ba344e4c117d90c',
    artist              = 'Dua Lipa',
    "availableTickets"  = 2,
    price               = '0.065 OCT'
WHERE id = '14';   -- Techno Underground

UPDATE concerts
SET concert_object_id   = '0x21961b8c6caa427e78d4236a97b2d6cf96d83e1aab712d3aff714fa087583d8a',
    artist              = 'Adele',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '15';   -- Blues Heritage Tour

