-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

UPDATE concerts
SET concert_object_id   = '0x5971f5df9e45735f1521a912af63a1cdba46af80cf7ecd91b0dbb9d25615c291',
    waitlist_object_id  = '0x33140048e48fe33cf01899ea524fd14243b4783c3134cedde6a5e274da1f0d00',
    artist              = 'Martin Garrix',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '1';   -- Neon Dreams Tour

UPDATE concerts
SET concert_object_id   = '0x2061d3e4a091229dd0529dd13f9027da2e5dfd15a3963fc0c8cdc65095303070',
    waitlist_object_id  = '0x9e2a5ca05721370c1aacb457f3ab8364cc3dbcc0536ced0923c54b4965f671a6',
    artist              = 'Taylor Swift',
    "availableTickets"  = 2,
    price               = '0.08 OCT'
WHERE id = '2';   -- Celestial Sound Experience

UPDATE concerts
SET concert_object_id   = '0xf1811ad9a458702ecffe85104223f3969d8e46d4d8791bec7d6cb7e4fc286f74',
    waitlist_object_id  = '0x6f3194f9e8b0e037242d0439b10f9799074bba67fba3c714bd7fea85e78605b2',
    artist              = 'Calvin Harris',
    "availableTickets"  = 2,
    price               = '0.12 OCT'
WHERE id = '3';   -- Blockchain Beats Festival

UPDATE concerts
SET concert_object_id   = '0x2c8fd04b39739ae0049e9e1601000f987a620ca8c571b027b0a42eae3bd9cac6',
    waitlist_object_id  = '0xd306f1df195f9ca8f981f6edb6576df25e96c7a692b12f6a1b0e33782fdfe241',
    artist              = 'Ed Sheeran',
    "availableTickets"  = 2,
    price               = '0.04 OCT'
WHERE id = '4';   -- Unplugged & Unchained

UPDATE concerts
SET concert_object_id   = '0x3fa74a4a8ceec075b2979a0c1a99fed3539246a5201f8c07bc58dc413b28b635',
    waitlist_object_id  = '0x23c115f9153796a11556f66d48affdaf65b4aa80455da3c4a44c8314dacae74a',
    artist              = 'Drake',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '5';   -- Decentralized Sound Tour

UPDATE concerts
SET concert_object_id   = '0x86659dd9d283bc3c3f8d5515aab157353a60244e6815ad4540141aec91d88d89',
    waitlist_object_id  = '0x04b1323f031c311d8d3b950108005dbb9f9c81d0e25b02b923e46eda83808421',
    artist              = 'Billie Eilish',
    "availableTickets"  = 2,
    price               = '0.06 OCT'
WHERE id = '6';   -- Galaxy Tour 2026

UPDATE concerts
SET concert_object_id   = '0xc399dd4365c160e74cf6c2200c3acd9585b555d816eb28334193b3ffc3d14470',
    waitlist_object_id  = '0x5e41b8758a43c3fb59edb8bd7a29a5569201b7a7744c5089b8fd7c557daab215',
    artist              = 'Bruno Mars',
    "availableTickets"  = 2,
    price               = '0.03 OCT'
WHERE id = '7';   -- Smooth Grooves Night

UPDATE concerts
SET concert_object_id   = '0xcc47a1ef7f7b365365ece68662022c5bfee027d9e55323df5a0cfcce1b493a2c',
    waitlist_object_id  = '0xc06ef59f09573d97c918998314e5019f3f8b4f1ded403854df678e87ebdb41db',
    artist              = 'The Weeknd',
    "availableTickets"  = 2,
    price               = '0.09 OCT'
WHERE id = '8';   -- Rock Revolution Tour

UPDATE concerts
SET concert_object_id   = '0xae9298f9f3d31c24d185c3b7be9740f76eea447e9638118c9d72556f72e5c8e2',
    waitlist_object_id  = '0x25c4c2bb7e59b14d0e1b23bbdc1ae9d087a887aef17a101ba3c841c3c3f7b9f2',
    artist              = 'Coldplay',
    "availableTickets"  = 2,
    price               = '0.10 OCT'
WHERE id = '9';   -- Blockchain Classics

UPDATE concerts
SET concert_object_id   = '0x0e0e30697349ecbfd3bc377a6e1f457e2a384f32f5f3947fa45e00a974a2557d',
    waitlist_object_id  = '0x7a1fa628e1b7cc4d72fd49f0511ce2e444499c5966232c51ed26fd16ccfa379e',
    artist              = 'Post Malone',
    "availableTickets"  = 2,
    price               = '0.045 OCT'
WHERE id = '10';   -- Country Roads Festival

UPDATE concerts
SET concert_object_id   = '0x9ba6a188ef9a92061be10c38ca952f5da30440c14a5c288ba4c94a45bdc206cd',
    waitlist_object_id  = '0x983ba031f6ade42a9012d2c3c1bf81b45d0f1d66f709b06e2d61e1a6024c427e',
    artist              = 'Linkin Park',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '11';   -- Metal Mayhem World Tour

UPDATE concerts
SET concert_object_id   = '0x32f0f32567b9ec3ff89a714012d5d1b0a466d74e14fc5892c904ba2c6b39b706',
    waitlist_object_id  = '0xbb2c0ce88254cada2f39d371f617bbc850b5aac51ff2b41802f2803b62ace848',
    artist              = 'Rihanna',
    "availableTickets"  = 2,
    price               = '0.035 OCT'
WHERE id = '12';   -- Island Rhythms Festival

UPDATE concerts
SET concert_object_id   = '0x15470e0181b4d2f822ae99e91073f6b60781a6da524fb8485942f96a6418d3f3',
    waitlist_object_id  = '0xe022db998b817201102df1106b894c775a835a41bf5d5bc9bfe8b7e80341d54d',
    artist              = 'Shakira',
    "availableTickets"  = 2,
    price               = '0.055 OCT'
WHERE id = '13';   -- Salsa Heat Night

UPDATE concerts
SET concert_object_id   = '0x5f4e6db6e9bdc3f77eab67c18d9edb9879d71e77eadd90d2bb162d9f3ec8e734',
    waitlist_object_id  = '0x051defdf8445257094a62d7d960f13d571da73fae6c1c2c93d55f6a11870c7c4',
    artist              = 'Dua Lipa',
    "availableTickets"  = 2,
    price               = '0.065 OCT'
WHERE id = '14';   -- Techno Underground

UPDATE concerts
SET concert_object_id   = '0x688488eee54d7202390353a9efc8fdeb3355a8586009ddff1e86dd126bf4aea1',
    waitlist_object_id  = '0x66720a01c1858ec4549968e2f7032999e029e30bbd897a25bef50d407c48d619',
    artist              = 'Adele',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '15';   -- Blues Heritage Tour

